### PR TITLE
Update app-lifecycle.md

### PR DESCRIPTION
**Pull request by MartyIX**

### CODE REVIEW

**Comment by davidbritch** [comment]
Hi @MartyIX 

For a user who copy/pastes this code they'd either need to have enabled nullables in their .csproj or add a #nullable enable to the MauiProgram class, right?

**Comment by MartyIX** [comment]
That's correct. Isn't it the default for new MAUI apps?

**Comment by davidbritch** [comment]
Afraid not. See https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj

**Comment by MartyIX** [comment]
Then I guess I should close this PR.

**Pull request closed without merging**
