### PR TITLE
Update customize handlers by using Platform (instead of Native)

### PR DESCRIPTION
**Pull request by janwiebe-jump**
Small changes to reflect the new Platform renaming in the handlers samples.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs-maui?pullRequest=390) <br/>All CLA requirements met.

**Comment by davidbritch** [comment]
Fixes #392
Fixes #396

**Review by davidbritch — APPROVED** [review]
Thanks @janwiebe-jump

**Comment by davidbritch** [comment]
@janwiebe-jump You need to sign the CLA before this PR can be merged. See the link several comments up from here.

**Pull request merged**
