### PR TITLE
Add info about nuget config

### PR DESCRIPTION
**Pull request by jamesmontemagno**

### CODE REVIEW

**Comment by davidbritch** [comment]
@jamesmontemagno Is this necessary? I haven't had to do that, and it "just works".

**Comment by jamesmontemagno** [comment]
hmmmm @Redth ?

**Comment by davidbritch** [comment]
A colleague installed MAUI P6, as his first ever MAUI install this week. He didn't have to add a NuGet entry.

**Comment by jamesmontemagno** [comment]
Yeah i just got word we don't need it so all good

**Pull request closed without merging**
