### PR TITLE
android-projects.md: New linker settings

### PR DESCRIPTION
**Pull request by breyed**
Document new options and defaults for `TrimMode`. I took my best guess at the new content, but couldn’t find defninitive documentation. FWIW, here’s an AI-generated [overview of the changes](https://g.co/gemini/share/c84935d1940b).

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/migration/android-projects.md](https://github.com/dotnet/docs-maui/blob/dc46d4bafa107283b624408b1f4e0402fa093263/docs/migration/android-projects.md) | [Xamarin.Android project migration](https://review.learn.microsoft.com/en-us/dotnet/maui/migration/android-projects?branch=pr-en-us-2211) |

### CODE REVIEW

**Comment by davidbritch** [comment]
@breyed This is the .NET 9 stuff?

**Comment by breyed** [comment]
According to dotnet/linker#3039, `TrimMode=full` and `TrimMode=partial` were introduced in .NET 7.

**Comment by jonathanpeppers** [comment]
I wouldn't use `TrimMode=full` (on mobile) unless you are on .NET 9:
* https://github.com/dotnet/maui/issues/18658

We plan to have more information about using this in a future preview.

**Comment by davidbritch** [comment]
Hi @breyed 

Thanks for the PR, and apologies for the delay in dealing with it. I've made some updates to it so that TrimMode=Full isn't mentioned (which is only available on mobile in .NET 9, and is still work-in-progress). We'll have more to say about TrimMode=Full once it's finalised.

**Review by davidbritch — APPROVED** [review]
Thanks @breyed

**Pull request merged**
