### PR TITLE
Add info about iOS full accuracy and GeoLocation

### LINKED ISSUE #531: iOS14+ Geolocation reduced accuracy support
https://github.com/dotnet/maui/pull/5826

@adegeo to decide if this has doc impact.

This is only available in the GA build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Version Independent ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Content: [Geolocation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?tabs=ios#distance-between-two-locations)
* Content Source: [docs/platform-integration/device/geolocation.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/geolocation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

### PR DESCRIPTION
**Pull request by adegeo**
@davidbritch I'm not sure what to say exactly about the plist file. The information in the bug didn't make sense to me. Perhaps you can help clairfy?

Fixes #531

### CODE REVIEW

**Comment by davidbritch** [comment]
So yeah, the doc needs to mention the Info.plist entry that's required. Basically users will need to add [this key](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600217-requesttemporaryfullaccuracyauth) to their Info.plist file. But the key is actually a [dictionary](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationtemporaryusagedescriptiondictionary).

It doesn't help that the description in the [PR](https://github.com/dotnet/maui/pull/5826) is copied from the [Essentials PR](https://github.com/xamarin/Essentials/pull/1739), without being updated. It should say: "The key TemporaryFullAccuracyUsageDescription was used for this purpose."

Joining all this together tells us that users will have to update their Info.plist with:

```xml
	<key>NSLocationTemporaryUsageDescriptionDictionary</key>
	<array>
		<dict>
			<key>TemporaryFullAccuracyUsageDescription</key>
			<string>Message to user will go here.</string>
		</dict>
	</array>
```

Obviously "Message to user will go here" should be something sensible like "Your location is used to XXXXXXX.".

I've not double-checked that the XML above is correct, but I think it is. So I'd recommend dumping it into an Info.plist, then opening the Info.plist in the Info.plist editor. If it's viewable in the editor, it's all good.

So I guess that's an update for the platform-specific setup bit of the doc (but specifying it's only required if users choose to use these new properties).

**Comment by adegeo** [comment]
The plist editor is always blank for me, so I can't tell if something is working or not. 😁

**Comment by adegeo** [comment]
Build error is unrelated but is due to the windows api migration going on. Should be fixed by monday

**Review by davidbritch — APPROVED** [review]
LGTM

**Pull request merged**
